CREATE TABLE ContractDetails( 
   id INT NOT NULL AUTO_INCREMENT,
   contractId INT,
   parentContractId INT,
   customContractId VARCHAR(20),   
   documentFileName VARCHAR(50) NOT NULL,
   contractName VARCHAR(50),
   legalEntityId INT,
   legalEntityName VARCHAR(100),
   counterPartyId INT,
   counterPartyName VARCHAR(100),
   contractTemplate VARCHAR(30),
   contractStartDate DATE,
   contractExpiryDate DATE,
   contractTypeId INT,
   contractSubTypeId INT,
   isLIBOR BOOLEAN,
   isAmendmentDoc BOOLEAN,
   currStatusId TINYINT,
   createdOn TIMESTAMP,
   createdBy VARCHAR(10),
   PRIMARY KEY ( id )
);