CREATE TABLE DerivativeFinancialDetails(
derivativeContractFinancialId INT NOT NULL AUTO_INCREMENT,
contractId INT NOT NULL,
counterPartyId INT,
jurisdiction VARCHAR(20),
governingLaw VARCHAR(20),
masterAgreementType VARCHAR(30),
masterAgreementActive CHAR,
creditSupportAnnex VARCHAR(30),
creditSupportAnnexActive CHAR,
Triparty CHAR,
creditSupByTitleTransfer CHAR,
initialMargin DOUBLE,
nettedAgainstVariation CHAR,
nettingEligible CHAR,
collateralEnforceability CHAR,
triggerDowngrade CHAR,
rehypothicationRights CHAR,
colleteralType VARCHAR(30),
validCurrencies VARCHAR(30),
baseCurrency VARCHAR(5),
valuationPercentage DOUBLE,
minTransferAmount DOUBLE,
thresholdAmount DOUBLE,
variationMargin DOUBLE,
PRIMARY KEY(derivativeContractFinancialId)
);