CREATE TABLE derivativeContract_Financial_Details(
derivativeContractFinancialId INT NOT NULL AUTO_INCREMENT,
contractId VARCHAR(20) NOT NULL,
counterPartyId INT NOT NULL,
jurisdiction VARCHAR(20) NOT NULL,
governingLaw VARCHAR(20) NOT NULL,
masterAgreementType VARCHAR(20),
masterAgreementActive CHAR NOT NULL,
creditSupportAnnex VARCHAR(20),
creditSupportAnnexActive CHAR NOT NULL,
Triparty CHAR NOT NULL,
creditSupByTitleTransfer CHAR NOT NULL,
initialMargin DOUBLE NOT NULL,
nettedAgainstVariation CHAR NOT NULL,
nettingEligible CHAR NOT NULL,
collateralEnforceability CHAR NOT NULL,
triggerDowngrade CHAR NOT NULL,
rehypothicationRights CHAR NOT NULL,
colleteralType VARCHAR(30),
validCurrencies VARCHAR(30),
baseCurrency VARCHAR(5) NOT NULL,
valuationPercentage DOUBLE,
minTransferAmount DOUBLE NOT NULL,
thresholdAmount DOUBLE NOT NULL,
variationMargin DOUBLE NOT NULL,
PRIMARY KEY(derivativeContractFinancialId)
); 