CREATE TABLE DocumentProcessingInfo(
documentProcessingId INT NOT NULL AUTO_INCREMENT,
IsLIBOR CHAR,
docPosition INT,
startpage INT,
startPagePosition INT,
startSnippet TEXT,
docFileName VARCHAR(100),
predictions VARCHAR(20),
legalEntityName VARCHAR(100),
counterPartyName VARCHAR(100),
startDate Date,
terminationDate Date,
amount VARCHAR(20),
currency VARCHAR(5),
fallbackPresent CHAR,
fallbackPosition INT,
fallbackPage INT,
fallbackText TEXT,
fallbackTextComplexity INT,
PRIMARY KEY(documentProcessingId)
);
