CREATE TABLE LoanFinancialDetails(
loanContractFinancialId INT NOT NULL AUTO_INCREMENT,
contractId INT NOT NULL,
counterPartyId INT,
loanAmount DOUBLE,
loanCurrency VARCHAR(10),
startDate DATE,
maturityDate DATE,
tenorMonths INT,
rateOfInterest DOUBLE,
loanTypeId TINYINT,
collateralInfo VARCHAR(100),
paymentSchedule TINYINT,
borrowerName VARCHAR(50),
lenderName VARCHAR(50),
adminAgentName VARCHAR(50),
jointLeadArrangerName VARCHAR(100),
coSyndicationAgentName VARCHAR(100),
coDocumentationAgentName VARCHAR(100),
PRIMARY KEY(loanContractFinancialId)
);